spring:
  application:
    name: ms-pipeline-metrobus
  datasource:
    url: jdbc:mysql://34.69.234.181:3306/pipeline_metrobus_db
    username: equiroz
    password: e1e2e3e4e5E
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
  #cloud:
    #gcp:
      #sql:
        #database-name: pipeline_metrobus_db
        #instance-connection-name: springgc-standard-291615:us-central1:springdb
        
server:
  port: 8080
  
datos-abiertos-cdmx.api-url: https://datos.cdmx.gob.mx/api/records/1.0/search
datos-abiertos-cdmx.api-dataset.alcaldias: /?dataset=alcaldias
datos-abiertos-cdmx.api-dataset.ubicaciones-metrobus: /?dataset=prueba_fetchdata_metrobus
datos-abiertos-cdmx.max-rows.alcaldias: 16
datos-abiertos-cdmx.max-rows.ubicaciones-metrobus: 207
  
#logging:
  #level:
    #org:
      #hibernate:
        #SQL: DEBUG
        #type:
          #descriptor:
            #sql:
              #BasicBinder: TRACE